// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfAspNet.CompiledModels
{
    public partial class MyContextModel
    {
        private MyContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cb15e0cd-5bb8-44be-b644-3174b99c4239"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var authorBook = AuthorBookEntityType.Create(this);
            var article = ArticleEntityType.Create(this);
            var author = AuthorEntityType.Create(this);
            var book = BookEntityType.Create(this);
            var errorLog = ErrorLogEntityType.Create(this);
            var meta = MetaEntityType.Create(this);
            var photo = PhotoEntityType.Create(this);
            var review = ReviewEntityType.Create(this);
            var user = UserEntityType.Create(this);

            AuthorBookEntityType.CreateForeignKey1(authorBook, author);
            AuthorBookEntityType.CreateForeignKey2(authorBook, book);
            AuthorEntityType.CreateForeignKey1(author, user);
            ReviewEntityType.CreateForeignKey1(review, book);

            AuthorEntityType.CreateSkipNavigation1(author, book, authorBook);
            BookEntityType.CreateSkipNavigation1(book, author, authorBook);

            AuthorBookEntityType.CreateAnnotations(authorBook);
            ArticleEntityType.CreateAnnotations(article);
            AuthorEntityType.CreateAnnotations(author);
            BookEntityType.CreateAnnotations(book);
            ErrorLogEntityType.CreateAnnotations(errorLog);
            MetaEntityType.CreateAnnotations(meta);
            PhotoEntityType.CreateAnnotations(photo);
            ReviewEntityType.CreateAnnotations(review);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "9.0.6");
            AddAnnotation("Proxies:ChangeTracking", false);
            AddAnnotation("Proxies:CheckEquality", false);
            AddAnnotation("Proxies:LazyLoading", true);
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
