// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SelfAspNet.CompiledModels;
using SelfAspNet.Models;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MyContext), typeof(MyContextModel))]
