name: Tweet on Push and Pull Request
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current timestamp
        id: get_ts
        run: |
          echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Post commit message on push
        if: github.event_name == 'push'
        uses: nearform-actions/github-action-notify-twitter@v1.2.3
        with:
          message: |
            Time: ${{ steps.get_ts.outputs.timestamp }}
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            URL: ${{ github.event.head_commit.url }}
          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: Post PR info to Twitter
        if: github.event_name == 'pull_request'
        uses: nearform-actions/github-action-notify-twitter@v1.2.3
        with:
          message: |
            Time: ${{ steps.get_ts.outputs.timestamp }}
            Repo: ${{ github.repository }}
            Branch: ${{ github.head_ref }}
            PR #${{ github.event.pull_request.number }}
            “${{ github.event.pull_request.title }}”
            by ${{ github.event.pull_request.user.login }}
            URL: ${{ github.event.pull_request.html_url }}
          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}